spring:
  application:
    name: greetings-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greetings-service:
  greeting: "Wassup"
  default-value: "Goddamn World"
